---
- hosts: all
  remote_user: ubuntu
  become: true
  tasks:
  - name: Instalar dependencias
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
      state: present
      update_cache: yes
  - name: Agregar llave GPG
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Agregar repositorio docker
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present
  - name: Instalar docker
    apt:
      name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
      state: latest
      update_cache: yes
  - name: Activar docker
    service:
      name: docker
      state: started
      enabled: yes
  - name: agregar usuario a grupo docker
    user:
      name: ubuntu
      state: present
      groups: docker
      append: yes
  handlers:
  - name: restart docker
    service: 
      name: docker 
      state: restarted